### ISSUE TITLE
Explicit license statement?

### ISSUE THREAD

**Issue by brodybits** [mkschreder/node-php#12]
Something like MIT or ISC would be great!

**Comment by mkschreder** [comment]
go with MIT.

**Comment by brodybits** [comment]
Awesome, thanks! Also, can we fix package.json?

I would be happy to issue a PR if you like.

**Comment by mkschreder** [comment]
Yes, you can add whatever fixes you deem necessary. Submit PR when you're
done and add yourself to contributors. I can then merge it into main repo..

**Comment by brodybits** [comment]
I would like to do this when I work on the solution to #13 (waiting for your response).

For contributors, I would rather just add a link in README.md to: https://github.com/mkschreder/node-php/graphs/contributors

Also, I would like to see the LICENSE file, which is standard for github. The COPYING file is generally though not always used for GPL or LGPL. I would rather rename the file but leave it up to you. Please let me know whether you want me to rename or copy the file.

I noticed that PR #1 (fix to get a visitor's IP) is still outstanding. Please let me know what the status is. I would also be happy to include that change or not when I push the changes, please let me know.
