### ISSUE TITLE
Current project status

### ISSUE THREAD

**Issue by DanielRuf** [mkschreder/node-php#24]
Hi, what is the current status of this project?

**Comment by mkschreder** [comment]
Abandoned.

**Comment by DanielRuf** [comment]
Ok, because this is not clear from the repo page (not archived or any info in the readme).

Are you looking for new maintainers or will it be archived?

**Comment by mkschreder** [comment]
Not archived. Since when people submit patches I merge them in if they make
sense. I just don't use node php in any current project anymore.

**Comment by DanielRuf** [comment]
Ah okay, thanks for the clarification and information.
